### PR TITLE
Update openssh sftp-server path

### LINKED ISSUE #72: Modern OpenSSH server configuration error on Ubuntu 18.04 LTS
Hi,

In the [openssh.md](docs/guidelines/openssh.md) guidelines, the sftp configuration is : 

    Subsystem sftp  /usr/lib/ssh/sftp-server -f AUTHPRIV -l INFO

But on Ubuntu 18.04 LTS, the sftp-server lib is in `/usr/lib/openssh/sftp-server`.

Do you think it's best to add a comment with os specific information? Or change the path ?

### PR DESCRIPTION
**Pull request by boTux**
Change the path of `/usr/lib/ssh/sftp-server` to `/usr/lib/openssh/sftp-server`.
Fix #72.

### CODE REVIEW

**Comment by gdestuynder** [comment]
the path is distribution dependent though i believe the default is `ssh` (as opposed to `openssh`)
thus, a comment as you proposed:  `# Check the path of sftp-server with `whereis sftp-server` to confirm the path of the lib.` seem like the best option

**Comment by gdestuynder** [comment]
@boTux would you like to modify your PR to just include the comment instead?

**Comment by gdestuynder** [comment]
no response - closing
feel free to re-open any time though
thanks!

**Comment by boTux** [comment]
@gdestuynder thanks for your reply.

I will add the comment on the modern & intermediate openssh-server configurations, but on the [docs/guidelines/openssh.md#protection-of-machine-keys section on line 276-277](https://github.com/boTux/infosec.mozilla.org/blob/patch-1/docs/guidelines/openssh.md#protection-of-machine-keys) should we do the same?

-----------------------------

Information :

- [Ubuntu/Debian](https://packages.ubuntu.com/bionic/amd64/openssh-sftp-server/filelist) :
   - `/usr/lib/openssh/sftp-server`
   - `/usr/lib/sftp-server -> openssh/sftp-server`
- Archlinux :
   - `/usr/lib/ssh/sftp-server`
- [CentOS 7](https://fedora.pkgs.org/29/fedora-x86_64/openssh-7.8p1-3.fc29.x86_64.rpm.html) 
   - `/usr/libexec/openssh/sftp-server`

The `whereis sftp-server` command might be the only safe way to indicate to the user the right path...

**Comment by gdestuynder** [comment]
@boTux how about writing the example with the `whereis` command? that way it probably works everywhere. I didn't realize each distro basically uses a different path

**Pull request closed without merging**
