### PR TITLE
Remove HPKP, which is obsolete

### PR DESCRIPTION
**Pull request by timmc**
I'm not aware of any browser that still recognizes public key pinning.

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning#browser_compatibility

**Comment by arroway** [comment]
Hi @timmc, better late than never: thanks for your PR, we're in the process of updating our documentation and will remove references to HPKP.
We'll get back to this PR when ready.
Thanks!

**Comment by gene1wood** [comment]
I think this has been resolved in #183 . Should this PR be closed?

**Comment by arroway** [comment]
yes, it's good to be closed, thanks.

**Pull request closed without merging**
